// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoHAmdgZ_eP9hD6gRsqr6qt5vHCOP5Ch0',
    appId: '1:137173225324:web:403034c017cfa9fe9e2d49',
    messagingSenderId: '137173225324',
    projectId: 'datingappregister',
    authDomain: 'datingappregister.firebaseapp.com',
    storageBucket: 'datingappregister.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dcpS-DmhvDt0xWwyFMyUUnMNk3vifiQ',
    appId: '1:137173225324:android:35463f279b69b2589e2d49',
    messagingSenderId: '137173225324',
    projectId: 'datingappregister',
    storageBucket: 'datingappregister.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU6T3gpLavXZ6bqUe5sUms0OZZkVFHMHE',
    appId: '1:137173225324:ios:be3759a4639a4ab49e2d49',
    messagingSenderId: '137173225324',
    projectId: 'datingappregister',
    storageBucket: 'datingappregister.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU6T3gpLavXZ6bqUe5sUms0OZZkVFHMHE',
    appId: '1:137173225324:ios:be3759a4639a4ab49e2d49',
    messagingSenderId: '137173225324',
    projectId: 'datingappregister',
    storageBucket: 'datingappregister.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoHAmdgZ_eP9hD6gRsqr6qt5vHCOP5Ch0',
    appId: '1:137173225324:web:f298a335bf779e3f9e2d49',
    messagingSenderId: '137173225324',
    projectId: 'datingappregister',
    authDomain: 'datingappregister.firebaseapp.com',
    storageBucket: 'datingappregister.firebasestorage.app',
  );
}
